/*
 * NumOS — STIX Two Math Font Constants
 * Auto-generated by scripts/extract_stix_math.py on 2026-05-31 19:51:50
 * Source font: C:\Users\Juan Ramón\Documents\Calculadora\assets\fonts\STIXTwoMath-Regular.ttf
 * Font UPM (unitsPerEm): 1000
 *
 * This file is part of NumOS.
 * Copyright (C) 2026 Juan Ramon
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * DO NOT EDIT MANUALLY — regenerated at build time.
 */

#pragma once

#include <cstdint>

namespace vpam {

/// STIX Two Math units-per-em (UPM).
/// All design-unit constants in kStixMathConstants are expressed relative to this value.
constexpr int16_t kStixMathUPM = 1000;

/// OpenType MATH table constants extracted from STIX Two Math.
///
/// Array index matches the OpenType spec serialization order (56 entries).
/// All values are in font design units (UPM = 1000).
/// Scale to pixels by multiplying by (fontSizePx / upm).
///
/// Access patterns (matching Mozilla Gecko's GetMathConstant dispatch):
///   [ 0– 1]  int16  — ScriptPercentScaleDown, ScriptScriptPercentScaleDown
///   [ 2– 3]  uint16 — DelimitedSubFormulaMinHeight, DisplayOperatorMinHeight
///   [ 4–54]  int16  — MathValueRecord.Value (DeviceTable offsets omitted)
///   [55]     uint16 — RadicalDegreeBottomRaisePercent
///
/// Reference: OpenType 1.9.1 spec, MATH table — MathConstants sub-table.
constexpr int16_t kStixMathConstants[56] = {
      70,  // [ 0] ScriptPercentScaleDown
      55,  // [ 1] ScriptScriptPercentScaleDown
    1325,  // [ 2] DelimitedSubFormulaMinHeight
    1800,  // [ 3] DisplayOperatorMinHeight
     150,  // [ 4] MathLeading
     258,  // [ 5] AxisHeight
     480,  // [ 6] AccentBaseHeight
     656,  // [ 7] FlattenedAccentBaseHeight
     210,  // [ 8] SubscriptShiftDown
     368,  // [ 9] SubscriptTopMax
     160,  // [10] SubscriptBaselineDropMin
     360,  // [11] SuperscriptShiftUp
     252,  // [12] SuperscriptShiftUpCramped
     120,  // [13] SuperscriptBottomMin
     230,  // [14] SuperscriptBaselineDropMax
     150,  // [15] SubSuperscriptGapMin
     380,  // [16] SuperscriptBottomMaxWithSubscript
      40,  // [17] SpaceAfterScript
     135,  // [18] UpperLimitGapMin
     300,  // [19] UpperLimitBaselineRiseMin
     135,  // [20] LowerLimitGapMin
     670,  // [21] LowerLimitBaselineDropMin
     470,  // [22] StackTopShiftUp
     780,  // [23] StackTopDisplayStyleShiftUp
     385,  // [24] StackBottomShiftDown
     690,  // [25] StackBottomDisplayStyleShiftDown
     150,  // [26] StackGapMin
     300,  // [27] StackDisplayStyleGapMin
     800,  // [28] StretchStackTopShiftUp
     590,  // [29] StretchStackBottomShiftDown
      68,  // [30] StretchStackGapAboveMin
      68,  // [31] StretchStackGapBelowMin
     585,  // [32] FractionNumeratorShiftUp
     640,  // [33] FractionNumeratorDisplayStyleShiftUp
     585,  // [34] FractionDenominatorShiftDown
     640,  // [35] FractionDenominatorDisplayStyleShiftDown
      68,  // [36] FractionNumeratorGapMin
     150,  // [37] FractionNumDisplayStyleGapMin
      68,  // [38] FractionRuleThickness
      68,  // [39] FractionDenominatorGapMin
     150,  // [40] FractionDenomDisplayStyleGapMin
     350,  // [41] SkewedFractionHorizontalGap
      68,  // [42] SkewedFractionVerticalGap
     175,  // [43] OverbarVerticalGap
      68,  // [44] OverbarRuleThickness
      68,  // [45] OverbarExtraAscender
     175,  // [46] UnderbarVerticalGap
      68,  // [47] UnderbarRuleThickness
      68,  // [48] UnderbarExtraDescender
      85,  // [49] RadicalVerticalGap
     170,  // [50] RadicalDisplayStyleVerticalGap
      68,  // [51] RadicalRuleThickness
      78,  // [52] RadicalExtraAscender
      65,  // [53] RadicalKernBeforeDegree
    -335,  // [54] RadicalKernAfterDegree
      55,  // [55] RadicalDegreeBottomRaisePercent
};

/// Enumeration index into kStixMathConstants for type-safe access.
/// Values match the OpenType MATH table serialization order.
enum class MathConstant : uint8_t {
    // ── int16 direct (0–1) ──
    ScriptPercentScaleDown                 = 0,
    ScriptScriptPercentScaleDown           = 1,

    // ── uint16 direct (2–3) ──
    DelimitedSubFormulaMinHeight           = 2,
    DisplayOperatorMinHeight               = 3,

    // ── MathValueRecord int16 values (4–54) ──
    MathLeading                            = 4,
    AxisHeight                             = 5,
    AccentBaseHeight                       = 6,
    FlattenedAccentBaseHeight              = 7,
    SubscriptShiftDown                     = 8,
    SubscriptTopMax                        = 9,
    SubscriptBaselineDropMin               = 10,
    SuperscriptShiftUp                     = 11,
    SuperscriptShiftUpCramped              = 12,
    SuperscriptBottomMin                   = 13,
    SuperscriptBaselineDropMax             = 14,
    SubSuperscriptGapMin                   = 15,
    SuperscriptBottomMaxWithSubscript      = 16,
    SpaceAfterScript                       = 17,
    UpperLimitGapMin                       = 18,
    UpperLimitBaselineRiseMin              = 19,
    LowerLimitGapMin                       = 20,
    LowerLimitBaselineDropMin              = 21,
    StackTopShiftUp                        = 22,
    StackTopDisplayStyleShiftUp            = 23,
    StackBottomShiftDown                   = 24,
    StackBottomDisplayStyleShiftDown       = 25,
    StackGapMin                            = 26,
    StackDisplayStyleGapMin                = 27,
    StretchStackTopShiftUp                 = 28,
    StretchStackBottomShiftDown            = 29,
    StretchStackGapAboveMin                = 30,
    StretchStackGapBelowMin                = 31,
    FractionNumeratorShiftUp               = 32,
    FractionNumeratorDisplayStyleShiftUp   = 33,
    FractionDenominatorShiftDown           = 34,
    FractionDenominatorDisplayStyleShiftDown = 35,
    FractionNumeratorGapMin                = 36,
    FractionNumDisplayStyleGapMin          = 37,
    FractionRuleThickness                  = 38,
    FractionDenominatorGapMin              = 39,
    FractionDenomDisplayStyleGapMin        = 40,
    SkewedFractionHorizontalGap            = 41,
    SkewedFractionVerticalGap              = 42,
    OverbarVerticalGap                     = 43,
    OverbarRuleThickness                   = 44,
    OverbarExtraAscender                   = 45,
    UnderbarVerticalGap                    = 46,
    UnderbarRuleThickness                  = 47,
    UnderbarExtraDescender                 = 48,
    RadicalVerticalGap                     = 49,
    RadicalDisplayStyleVerticalGap         = 50,
    RadicalRuleThickness                   = 51,
    RadicalExtraAscender                   = 52,
    RadicalKernBeforeDegree                = 53,
    RadicalKernAfterDegree                 = 54,

    // ── uint16 standalone (55) ──
    RadicalDegreeBottomRaisePercent        = 55,

    COUNT                                  = 56
};

}  // namespace vpam
