/*
 * NumOS — STIX Two Math Font Declarations
 * Copyright (C) 2026 Juan Ramon
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * LVGL font declarations for the three STIX Two Math font sizes:
 *   stix_math_18  — Display/Text style  (18pt)
 *   stix_math_12  — Script style         (12pt, ~70% of display)
 *   stix_math_8   — ScriptScript style   ( 8pt, ~55% of script)
 *
 * Generated by scripts/generate_stix_math_font.sh using lv_font_conv.
 */

#pragma once

#include <lvgl.h>

#ifdef __cplusplus
extern "C" {
#endif

LV_FONT_DECLARE(stix_math_18);
LV_FONT_DECLARE(stix_math_12);
LV_FONT_DECLARE(stix_math_8);

#ifdef __cplusplus
}
#endif
